### ISSUE TITLE
11.4 AQS的主要方法源码解析--完善

### ISSUE THREAD

**Issue by lpe234** [RedSpider1/concurrent#108]
这些方法虽然都是protected方法，但是它们并没有在AQS具体实现，而是直接抛出异常（虽然不知道这里为什么不使用抽象方法的实现方式）：

---
这块不使用抽象方法的原因主要是：假如只需要实现一个独占同步器，具体类仅需要重写`tryAcquire`，`tryRelease`两个方法即可，无需再实现其他抽象方法。

**Comment by yasinshaw** [comment]
最新版已添加上原因。感谢~
