### ISSUE TITLE
文档bug

### ISSUE THREAD

**Issue by kender1314** [RedSpider1/concurrent#110]
![image](https://user-images.githubusercontent.com/37035331/109250416-9fcb7900-7824-11eb-910a-4a5c128cfd85.png)
这里有bug哦
![image](https://user-images.githubusercontent.com/37035331/109250437-ad80fe80-7824-11eb-8c95-9e814612d776.png)
正确的应该是这样的
`        Thread thread = new Thread(runnableDemo);
        thread.start();`

**Comment by yasinshaw** [comment]
你写法不对吧，按照文章中的写法没问题呀。
