### ISSUE TITLE
17.4.3 CyclicBarrier案例，不需要主动重置屏障“cyclicBarrier.reset(); // 重置屏障”

### ISSUE THREAD

**Issue by IronMan-Liu** [RedSpider1/concurrent#114]
在17.4.3 CyclicBarrier案例中，PreTaskThread的run()里不需要主动重置屏障（即代码中“cyclicBarrier.reset(); // 重置屏障”），因为看源码中可知，“cyclicBarrier.await()”这一句代码在达到线程数之后会自动调用breakBarrier()来完成重置屏障，并调用nextGeneration()进入下一代。并且经过我的测试，注释掉代码中“cyclicBarrier.reset(); // 重置屏障”这句，程序运行结果仍然正确。非常希望得到作者的回复，谢谢！

**Comment by yasinshaw** [comment]
确实是不需要的。感谢勘误。
下文也提到了，一旦调用await()方法的线程数量等于构造方法中传入的任务总量（这里是3），就代表达到屏障了。
