### ISSUE TITLE
笔误修正

### ISSUE THREAD

**Issue by javasingle** [RedSpider1/concurrent#116]
所以有时候，为了让任务有能够取消的功能，就使用Callable来代替Runnable。如果为了可取消性而使用 Future但又不提供可用的结果，则可以声明 Future<?>形式类型、并返回 null作为底层任务的结果。

文中就使用Callable来代替Runnable是不是应该是使用Future代替Runable

**Comment by yasinshaw** [comment]
与Runnable对应的是Callable，只是Callable使用了Future作为返回值。所以Future其实应该是和Runnable的返回值void 对应，两者不是同一个级别的概念哈。
