### ISSUE TITLE
第二章第八节的两张图片是不是显示不了？

### ISSUE THREAD

**Issue by Crandy** [RedSpider1/concurrent#119]
在redspider.gitbook.io中，第二篇，第八节 volatile中，对应的“volatile内存示意图”和“内存屏障”两张图片，在页面显示不了

**Comment by yasinshaw** [comment]
gitbook.io那边显示可能是有些异常。推荐看pdf或者去我们自己的域名在线看哦：http://concurrent.redspider.group
