### ISSUE TITLE
负负得正问题

### ISSUE THREAD

**Issue by NahFang** [RedSpider1/concurrent#123]
原理篇中 happens - before 章节中的最后，JMM对于重排序的策略中存在笔误，可能是作者当时急于表达对于改变结果的重排序的禁止，从而double禁止变为了允许。哈哈哈哈~
![image](https://user-images.githubusercontent.com/58882103/174626885-00c82bb5-2e52-4f1c-91c1-26e78040c8fd.png)

**Comment by yasinshaw** [comment]
最新版本应该已经订正了。http://concurrent.redspider.group/article/02/7.html
