### ISSUE TITLE
如果时间允许可以更新一下内容

### ISSUE THREAD

**Issue by NahFang** [RedSpider1/concurrent#124]
比如说并发容器中ConrrentHashMap 在1.8时结构变为了Node数组的形式，并且希望能够多扩充一些知识点。

**Comment by yasinshaw** [comment]
这个文章系列偏底层理论一些，对工具类的介绍确实不多。CHM之前在这一章节介绍了：http://concurrent.redspider.group/article/03/15.html
如果感兴趣可以配合我写了这两篇文章看看源码，我待会儿附在书上：
https://yasinshaw.com/articles/27
https://yasinshaw.com/articles/30
