### ISSUE TITLE
我又来了！

### ISSUE THREAD

**Issue by NahFang** [RedSpider1/concurrent#125]
在JDK工具篇中的 Fork/Join 文章

**相关截图或文字**
![1656227447(1)](https://user-images.githubusercontent.com/58882103/175803677-f39b6a20-d903-4c12-a7a0-cd4da205761a.png)

**疑问**

在对工作窃取算法的描述中，说明了当一个线程在完成自己的任务队列的任务后会在其它双端队列的尾端窃取任务执行，但是在如上图所示的，介绍双端队列时，又提到窃取的任务应属于任务所属队列的首部。感觉有点矛盾，但是我是新手，所以不确定两个是否是同一概念，但是在查询其它资料后，对于双端队列的说法都是如书 在介绍工作窃取算法时所说的一样，是在任务所属尾端拿任务执行。

**Comment by yasinshaw** [comment]
这里是笔误 最新版的应该已经改过了：http://concurrent.redspider.group/article/03/18.html
