### ISSUE TITLE
实现Runnable接口--内容修订

### ISSUE THREAD

**Issue by GeTieJun** [RedSpider1/concurrent#130]
**章节**
第一篇
第二节
2.1.2 实现Runnable接口

**相关截图或文字**
![image](https://user-images.githubusercontent.com/26588377/197709934-b6655156-5246-4356-8c34-aa637eedb727.png)
这里启动线程方式不对

**修正意见**
new Thread(new MyThread()).start();

**Comment by yasinshaw** [comment]
> **章节** 第一篇 第二节 2.1.2 实现Runnable接口
> 
> **相关截图或文字** ![image](https://user-images.githubusercontent.com/26588377/197709934-b6655156-5246-4356-8c34-aa637eedb727.png) 这里启动线程方式不对
> 
> **修正意见** new Thread(new MyThread()).start();

这个已经改过了哈。可以看github的内容或者去网站上看：http://concurrent.redspider.group/article/01/2.html
