### ISSUE TITLE
Callable接口没有取消任务的功能

### ISSUE THREAD

**Issue by SealedJn** [RedSpider1/concurrent#131]
**章节**
第2章
2.2.2 Future接口

**相关截图或文字**
![深入浅出java多线程错误](https://user-images.githubusercontent.com/42583697/199662359-f70f3ecd-15df-4408-b544-8b759dd5ee9b.png)

**修正意见**
应该修改为：
就使用Future来代替Runnable

**Comment by yasinshaw** [comment]
> 

和Runnable对应的应该是Callable哈。Future只是它的返回值。
