### ISSUE TITLE
图床失效

### ISSUE THREAD

**Issue by yangshijing** [RedSpider1/concurrent#38]
![image](https://user-images.githubusercontent.com/26130739/71499034-c3e69f80-2899-11ea-8c74-4d284ab9ae72.png)

**Comment by yasinshaw** [comment]
你好，我们没有用图床哈，所有图片都是放在源文件下面的imgs/文件夹下的。可能是你的这个marddown阅读器显示的问题，你看看你这个阅读器的源码模式指向哪个路径呢？我们有在线版本的哈：http://concurrent.redspider.group/
