### ISSUE TITLE
不同锁保护同一个资源的问题

### ISSUE THREAD

**Issue by youthlin** [RedSpider1/concurrent#40]
article/01/5.md
5.3-信号量

```
public class Signal {
    private static volatile int signal = 0;

    static class ThreadA implements Runnable {
        @Override
        public void run() {
            while (signal < 5) {
                if (signal % 2 == 0) {
                    System.out.println("threadA: " + signal);
                    synchronized (this) {
                        signal++;
                    }
                }
            }
        }
    }

    static class ThreadB implements Runnable {
        @Override
        public void run() {
            while (signal < 5) {
                if (signal % 2 == 1) {
                    System.out.println("threadB: " + signal);
                    synchronized (this) {
                        signal = signal + 1;
                    }
                }
            }
        }
    }

    public static void main(String[] args) throws InterruptedException {
        new Thread(new ThreadA()).start();
        Thread.sleep(1000);
        new Thread(new ThreadB()).start();
    }
}

// 输出：
threadA: 0
threadB: 1
threadA: 2
threadB: 3
threadA: 4
```
我们可以看到，使用了一个volatile变量signal来实现了“信号量”的模型。这里需要注意的是，volatile变量需要进行原子操作。signal++并不是一个原子操作，所以我们需要使用synchronized给它“上锁”。

---

这两个地方对 this 进行 synchronized 好像不对吧，两个 this 不是同一个锁呢，可以改成 `synchronized(Signal.class)` ？

**Comment by jasonzhangz** [comment]
为何要强调同一把锁？

**Comment by jasonzhangz** [comment]
> article/01/5.md
> 5.3-信号量
> 
> ```
> public class Signal {
>     private static volatile int signal = 0;
> 
>     static class ThreadA implements Runnable {
>         @Override
>         public void run() {
>             while (signal < 5) {
>                 if (signal % 2 == 0) {
>                     System.out.println("threadA: " + signal);
>                     synchronized (this) {
>                         signal++;
>                     }
>                 }
>             }
>         }
>     }
> 
>     static class ThreadB implements Runnable {
>         @Override
>         public void run() {
>             while (signal < 5) {
>                 if (signal % 2 == 1) {
>                     System.out.println("threadB: " + signal);
>                     synchronized (this) {
>                         signal = signal + 1;
>                     }
>                 }
>             }
>         }
>     }
> 
>     public static void main(String[] args) throws InterruptedException {
>         new Thread(new ThreadA()).start();
>         Thread.sleep(1000);
>         new Thread(new ThreadB()).start();
>     }
> }
> 
> // 输出：
> threadA: 0
> threadB: 1
> threadA: 2
> threadB: 3
> threadA: 4
> ```
> 
> 我们可以看到，使用了一个volatile变量signal来实现了“信号量”的模型。这里需要注意的是，volatile变量需要进行原子操作。signal++并不是一个原子操作，所以我们需要使用synchronized给它“上锁”。
> 
> 这两个地方对 this 进行 synchronized 好像不对吧，两个 this 不是同一个锁呢，可以改成 `synchronized(Signal.class)` ？

为何要强调同一把锁？

**Comment by yasinshaw** [comment]
> article/01/5.md
> 5.3-信号量
> 
> ```
> public class Signal {
>     private static volatile int signal = 0;
> 
>     static class ThreadA implements Runnable {
>         @Override
>         public void run() {
>             while (signal < 5) {
>                 if (signal % 2 == 0) {
>                     System.out.println("threadA: " + signal);
>                     synchronized (this) {
>                         signal++;
>                     }
>                 }
>             }
>         }
>     }
> 
>     static class ThreadB implements Runnable {
>         @Override
>         public void run() {
>             while (signal < 5) {
>                 if (signal % 2 == 1) {
>                     System.out.println("threadB: " + signal);
>                     synchronized (this) {
>                         signal = signal + 1;
>                     }
>                 }
>             }
>         }
>     }
> 
>     public static void main(String[] args) throws InterruptedException {
>         new Thread(new ThreadA()).start();
>         Thread.sleep(1000);
>         new Thread(new ThreadB()).start();
>     }
> }
> 
> // 输出：
> threadA: 0
> threadB: 1
> threadA: 2
> threadB: 3
> threadA: 4
> ```
> 
> 我们可以看到，使用了一个volatile变量signal来实现了“信号量”的模型。这里需要注意的是，volatile变量需要进行原子操作。signal++并不是一个原子操作，所以我们需要使用synchronized给它“上锁”。
> 
> 这两个地方对 this 进行 synchronized 好像不对吧，两个 this 不是同一个锁呢，可以改成 `synchronized(Signal.class)` ？

这位同学的问题有点意思的哈。先给你的认真点赞。
然后我回答一下，这里为什么不用this，为什么不用同一个锁？因为这个地方我们想体现的`volatile`关键字的可见性哈。我们考虑两种情况：
- 如果你用同一把锁：
  - 加了volatile， 结果总是12345；
  - 不加volatile， 结果也是总是12345；

- 如果你不用同一把锁：
  - 加了volatile, 结果总是12345；
  - 不加volatile，结果可能不是12345；

这样就很明白了吧？如果用同一把锁，从体验结果上来讲，是体现不出volatile的可见性的。而两把不同的锁则可以。所以这个地方我们刻意用了两把锁，就是为了体现volatile的可见性。

当然，我们的文字部分可能没有说明到这一点，所以给你带来了这个困惑，我们会尽快把这个原因加到文字部分哈，谢谢反馈~

**Comment by youthlin** [comment]
我觉得这里其实不用加 synchronized 也可以的

**Comment by youthlin** [comment]
这里分别在各自线程 synchronized 自身，应该是没必要的吧？
看起来感觉像是 syncronized(new Object()) 一样的奇怪……

**Comment by youthlin** [comment]
> 我觉得这里其实不用加 synchronized 也可以的

因为如 2 楼所说，volatile 关键字已经可以保证可见性了，而且 run 里面是 while 循环，一个线程对 signal 写入了，可以使另一个线程在下次循环读到最新值。

**Comment by yasinshaw** [comment]
> > 我觉得这里其实不用加 synchronized 也可以的
> 
> 因为如 2 楼所说，volatile 关键字已经可以保证可见性了，而且 run 里面是 while 循环，一个线程对 signal 写入了，可以使另一个线程在下次循环读到最新值。

这里是需要加锁的哈。其原因在文中也提到：signal++并不是一个原子操作，所以我们需要使用synchronized给它“上锁”。

因为`signal++`和`signal  = signal + 1`都不是原子操作，它们会先从内存“读”出signal的值，然后计算，然后写入新的值到内存。

如果我们不给它“上锁”，就算我们给signal用了volatile关键字，有“可见性”，也会有可能造成错误。

试想这种情况：
两个线程同时”读“到一个一样的值（比如signal = 3），然后两边分别进行 + 1操作，写入数据库。这种情况下，结果就会输出12344

总结：加锁是为了保证”读取- 修改值 - 写入“这个操作的原子性。

**Comment by youthlin** [comment]
可是这里根本不可能两边同时加啊，因为有模 2 的判断啊？

**Comment by yasinshaw** [comment]
em.. 这么一说是的，针对这个case，外面有模2的判断，里面不加锁也是可行的，因为**只有2个线程**，所以根据目前的程序，就算`signal++ `不是原子操作，也不**会有另一个线程在这个操作中间修改**`signal`的值。
感谢指出这个问题，我们会尽快修改一下程序和描述。

**Comment by wqhyw** [comment]
虽然`signal++`不是原子操作，但是对于这个例子取模操作我感觉实际上就是一个隐含的锁呢。

<img width="661" alt="image" src="https://user-images.githubusercontent.com/11343739/78317756-bb3aef00-7595-11ea-931e-e09cf3fbf2f2.png">

**Comment by wqhyw** [comment]
> 虽然`signal++`不是原子操作，但是对于这个例子取模操作我感觉实际上就是一个隐含的锁呢。
> 
> <img alt="image" width="661" src="https://user-images.githubusercontent.com/11343739/78317756-bb3aef00-7595-11ea-931e-e09cf3fbf2f2.png">

但是最后这个`thread0: 20`着实令人困惑，加不加锁都会偶尔出现。。
