### ISSUE TITLE
第7页，有些内容读不通

### ISSUE THREAD

**Issue by zhaoxjmail** [RedSpider1/concurrent#41]
总之，进程和线程的提出极⼤的提⾼了操作提供的性能。进程让操作系统的并发性 成为了可能，⽽线程让进程的内部并发成为了可能。

"操作提供"的性能应该是"操作系统"的性能?

**Comment by initial-y** [comment]
> 总之，进程和线程的提出极⼤的提⾼了操作提供的性能。进程让操作系统的并发性 成为了可能，⽽线程让进程的内部并发成为了可能。
> 
> "操作提供"的性能应该是"操作系统"的性能?

感谢勘误, 已修改
