### ISSUE TITLE
第132页有个单词拼错了

### ISSUE THREAD

**Issue by yiqzq** [RedSpider1/concurrent#42]
RecursiveRask 应该是RecursiveTask

**Comment by yiqzq** [comment]
还有想问一下第133页关于WorkQueue中,

> 当⼯作线程在处理⾃⼰的⼯作队列时，会从队列尾取任务来执⾏（LIFO）；如果是 窃取其他队列的任务时，窃取的任务位于所属任务队列的队⾸（FIFO）。

是不是反了,工作线程不是从队首取元素

**Comment by yasinshaw** [comment]
已修改，感谢提出。
