### ISSUE TITLE
2.1.2 实现Runnable接口

### ISSUE THREAD

**Issue by aloofcoder** [RedSpider1/concurrent#43]
应该是 new Thread(new MyThread()).start() 这样吧

**Comment by davids-dot** [comment]
第一篇：基础篇
  第二章 Java多线程入门类和接口 
2.1.2 实现Runnable接口 
Demo 类的 main 方法的第一句
 new MyThread().start(); 
  MyThread 没有start 方法，编译不通过

**Comment by yongmingcode** [comment]
我也认为第一篇：基础篇，2.1.2 实现Runnable接口，这部分代码Demo有问题
应该是：1.先创建Thread类的对象，2.再调用start()方法

**Comment by yongmingcode** [comment]
我也认为第一篇：基础篇，2.1.2 实现Runnable接口，这部分代码Demo有问题
应该是：1.先创建Thread类的对象，2.再调用start()方法
具体可以参考文档：http://itmyhome.com/java-api/java/lang/Runnable.html

**Comment by initial-y** [comment]
> 应该是 new Thread(new MyThread()).start() 这样吧

感谢勘误， 已修改

**Comment by initial-y** [comment]
> 第一篇：基础篇
> 第二章 Java多线程入门类和接口
> 2.1.2 实现Runnable接口
> Demo 类的 main 方法的第一句
> new MyThread().start();
> MyThread 没有start 方法，编译不通过

感谢勘误 已修改

**Comment by initial-y** [comment]
> 我也认为第一篇：基础篇，2.1.2 实现Runnable接口，这部分代码Demo有问题
> 应该是：1.先创建Thread类的对象，2.再调用start()方法
> 具体可以参考文档：http://itmyhome.com/java-api/java/lang/Runnable.html

感谢勘误 已修改
