### ISSUE TITLE
关于Timed_waiting的解释有误

### ISSUE THREAD

**Issue by crespo09** [RedSpider1/concurrent#44]
第26页关于TIMED_WAITING的解释：
"这时你还是线程t1，你改bug的同事是线程t2。t2让t1等待了指定时间，t1先主动释放了锁。此时t1等待期间就属于TIMED_WAITING状态。"
正确的说法应该是当线程调用sleep(long millis),wait(long millis),join(long millis)这些方法之后会转入TIME_WATING状态，但是**持有的锁并不会释放**。

**Comment by yasinshaw** [comment]
感谢反馈，实际上sleep方法不会释放锁，而wait和join会。会尽快修改~
