### ISSUE TITLE
第二篇 7 重排序与happens-before

### ISSUE THREAD

**Issue by icysea-blog** [RedSpider1/concurrent#46]
原文：
重排序有两类，JMM对这两类重排序有不同的策略：
会改变程序执行结果的重排序，比如 A -> C，JMM要求编译器和处理器都不许禁止这种重排序。
不会改变程序执行结果的重排序，比如 A -> B，JMM对编译器和处理器不做要求，允许这种重排序。

JMM要求编译器和处理器都不许禁止这种重排序 
是否应改为：JMM要求编译器和处理器禁止这种重排序

**Comment by yasinshaw** [comment]
我看源文件和pdf目前都是 “JMM要求编译器和处理器都禁止这种重排序”

**Comment by icysea-blog** [comment]
https://redspider.gitbook.io/concurrent/di-er-pian-yuan-li-pian/7
在gitbook上
