### ISSUE TITLE
用例代码问题

### ISSUE THREAD

**Issue by hineQi** [RedSpider1/concurrent#48]
2.1.2 实现Runnable接口
Runnable的用例：
new MyThread().start();这样不对吧
是不是应该new Thread(new MyThread()).start();

**Comment by initial-y** [comment]
> 2.1.2 实现Runnable接口
> Runnable的用例：
> new MyThread().start();这样不对吧
> 是不是应该new Thread(new MyThread()).start();

感谢勘误 问题已经修改, pdf可能还没同步更新
建议通过[深入浅出Java多线程](http://concurrent.redspider.group/)获取最新版本
