### ISSUE TITLE
部分文字错误

### ISSUE THREAD

**Issue by lpe234** [RedSpider1/concurrent#49]
当前仅发现：`article/02/9.md`。

develop分支。

1. 154行
所以，如果应用程序里所有的锁通常【出于】(处于)竞争状态，

2. 209行
【果】(如果|若)线程获得锁后调用`Object.wait`方法，

3. 235行
| 追求吞吐量。同步块执行【速度】(时间)较长。     |

**Comment by initial-y** [comment]
> 当前仅发现：`article/02/9.md`。
> 
> develop分支。
> 
> 1. 154行
>    所以，如果应用程序里所有的锁通常【出于】(处于)竞争状态，
> 2. 209行
>    【果】(如果|若)线程获得锁后调用`Object.wait`方法，
> 3. 235行
>    | 追求吞吐量。同步块执行【速度】(时间)较长。     |

感谢勘误, 已修改 [synchronized与锁](http://concurrent.redspider.group/article/02/9.html)
