### ISSUE TITLE
第15章，图缺失

### ISSUE THREAD

**Issue by yasinshaw** [RedSpider1/concurrent#50]
第15章，图缺失：

有些方法需要跨段，比如size()、isEmpty()、containsValue()，它们可能需要锁定整个表而而不仅仅是某个段，这需要按顺序锁定所有段，操作完毕后，又按顺序释放所有段的锁。如下图：

**Comment by initial-y** [comment]
> 第15章，图缺失：
> 
> 有些方法需要跨段，比如size()、isEmpty()、containsValue()，它们可能需要锁定整个表而而不仅仅是某个段，这需要按顺序锁定所有段，操作完毕后，又按顺序释放所有段的锁。如下图：

已修改 [并发容器集合](http://concurrent.redspider.group/article/03/15.html)
