### ISSUE TITLE
第八章 volatile 部分小错误

### ISSUE THREAD

**Issue by liangtingchen** [RedSpider1/concurrent#51]
#### 8.2.1 禁止重排序小节的图片
- "禁止下面所有的**鞋**操作“ 应该是”**写**操作“
>![image](https://user-images.githubusercontent.com/57647779/79760581-dc039280-8352-11ea-9be8-b567fb59a470.png)

#### 8.3 volatile的用途
- 末尾段写了volatile在单例模式中的应用，原文为”比如线程A在第10行执行了步骤1和步骤3，但是步骤2还没有执行完。**这个时候线程A执行到了第7行，它会判定instance不为空**，然后直接返回了一个未初始化完成的instance！“，应该是”**这个时候B线程执行到了第七行**“，原文的意思应该是想说另外一个线程执行到了第七行，判断instance不为空，获得了一个没有初始化完成的instance

**Comment by initial-y** [comment]
> #### 8.2.1 禁止重排序小节的图片
> * "禁止下面所有的**鞋**操作“ 应该是”**写**操作“
> 
> > ![image](https://user-images.githubusercontent.com/57647779/79760581-dc039280-8352-11ea-9be8-b567fb59a470.png)
> 
> #### 8.3 volatile的用途
> * 末尾段写了volatile在单例模式中的应用，原文为”比如线程A在第10行执行了步骤1和步骤3，但是步骤2还没有执行完。**这个时候线程A执行到了第7行，它会判定instance不为空**，然后直接返回了一个未初始化完成的instance！“，应该是”**这个时候B线程执行到了第七行**“，原文的意思应该是想说另外一个线程执行到了第七行，判断instance不为空，获得了一个没有初始化完成的instance

感谢勘误 , 文字部分已修改, 图稍后修改 [volatile](http://concurrent.redspider.group/article/02/8.html)
