### ISSUE TITLE
"2.2.2 Future接口"章节描述疑问

### ISSUE THREAD

**Issue by TeeMoCode** [RedSpider1/concurrent#56]
2.2.2 Future接口 章节的最后一段有这样的描述"所以有时候，为了让任务有能够取消的功能，就使用Callable来代替Runnable。",这里是不是使用Future来替代Runnable?

**Comment by yasinshaw** [comment]
不是的哈，Callable会返回Future的。一边是用Callable和Runnable做比较。Future只是用来跟Callable配套使用的。
