### ISSUE TITLE
4.3.4 线程中断——代码有误

### ISSUE THREAD

**Issue by braydenwong** [RedSpider1/concurrent#60]
isInterrupted和interrupt是实例方法，不能直接通过类名调用。

**Comment by yasinshaw** [comment]
请提供具体的章节号

**Comment by braydenwong** [comment]
> 请提供具体的章节号

基础篇-第四章 Java线程的状态及主要转化方法 然后搜我这个issues的title

**Comment by initial-y** [comment]
> isInterrupted和interrupt是实例方法，不能直接通过类名调用。

你好，感谢反馈， 此处`Thread.isInterrupted()`的意思是Thread类的interrupt方法，并不是通过Thread类调用的意思。
其他情况与此类似。
