### ISSUE TITLE
10.4 原子操作-AtomicInteger类源码简析——单词拼写错误

### ISSUE THREAD

**Issue by braydenwong** [RedSpider1/concurrent#61]
原文：根据本文第一篇参考文章（文末链接），它跟volitile有关。
错误：volitile拼写错误，应为volatile

**Comment by initial-y** [comment]
> 原文：根据本文第一篇参考文章（文末链接），它跟volitile有关。
> 错误：volitile拼写错误，应为volatile

感谢反馈， 已修复。
