### ISSUE TITLE
11.1 AQS简介——错别字

### ISSUE THREAD

**Issue by braydenwong** [RedSpider1/concurrent#62]
原文：当然，我们自己也能利用AQS非常轻松容易地构造出符合我们自己需求的同步器，只要之类实现它的几个protected方法就可以了，在下文会有详细的介绍。

错误：...只要之类实现....，应为子类而不是之类

**Comment by initial-y** [comment]
> 原文：当然，我们自己也能利用AQS非常轻松容易地构造出符合我们自己需求的同步器，只要之类实现它的几个protected方法就可以了，在下文会有详细的介绍。
> 
> 错误：...只要之类实现....，应为子类而不是之类

感谢反馈， 已修复。
