### ISSUE TITLE
4.2.2 关于线程 RUNNABLE 状态的疑惑

### ISSUE THREAD

**Issue by stul-5230** [RedSpider1/concurrent#64]
Java 中的注释写到：
/**
 * Thread state for a runnable thread.  A thread in the runnable
 * state is executing in the Java virtual machine but it may
 * be waiting for other resources from the operating system
 * such as processor.
 */
注释中描述的是 “也许是在等待其他操作系统的资源” 。
您在书中的描述是 “Java线程的RUNNABLE状态其实是包括了传统操作系统线程的 ready 和 running 两个状态的。"

在等待系统资源的时候，为何不是处于 waiting 状态？那这里应该是 waiting 和 running状态吗？ 这是我的一个疑惑点，希望您可以帮助理解一下。

**Comment by initial-y** [comment]
> * Java线程的RUNNABLE状态

你好，感谢反馈。由操作系统状态转换图所示，操作系统的ready表示线程已经被创建在**等待**时间片的分配（such as processor）,而waiting状态， 你注意一下， waiting状态只能由running状态触发（IO/event waiting），这里你可以类比一下Java线程Runnable状态到Waiting或者Timed_Wating的转换（event wating），操作系统的wating状态是可以和Java线程的Waiting状态对应得上的。
不知道有没有继续解答你的疑惑， 如仍有疑问，欢迎继续交流。
