### ISSUE TITLE
重排序与happens-before章节下，有笔误。

### ISSUE THREAD

**Issue by carycode4fun** [RedSpider1/concurrent#65]
会改变程序执行结果的重排序，比如 A -> C，JMM要求编译器和处理器都~~不许~~禁止这种重排序。

应该是JMM要求编译器和处理器都必须禁止这种重排序。

**Comment by initial-y** [comment]
> 会改变程序执行结果的重排序，比如 A -> C，JMM要求编译器和处理器都~不许~禁止这种重排序。
> 
> 应该是JMM要求编译器和处理器都必须禁止这种重排序。

感谢反馈 [第七章 重排序与happens-before](http://concurrent.redspider.group/article/02/7.html)，已修复
