### ISSUE TITLE
当调用一个锁对象的wait或notify方法时，如当前锁的状态是偏向锁或轻量级锁则会先膨胀成重量级锁。

### ISSUE THREAD

**Issue by ambition0802** [RedSpider1/concurrent#67]
9.2.4章节中，有下面一段话：
如果线程获得锁后调用Object.wait方法，则会将线程加入到WaitSet中，当被Object.notify唤醒后，会将线程从WaitSet移动到Contention List或EntryList中去。需要注意的是，**_当调用一个锁对象的wait或notify方法时，如当前锁的状态是偏向锁或轻量级锁则会先膨胀成重量级锁_**。
对于这段话中加粗斜体的这句话，只讲了现象，具体原因请问是什么呢?

**Comment by yasinshaw** [comment]
这是一个很好的问题。
因为JDK其实只为sync关键字做了优化，有“偏向、轻量级、重量级锁”的概念。看JVM源码，会发现所谓重量级锁，是使用一个ObjectMonitor对象来实现的，它的底层就是使用的操作系统的互斥量来实现的。
而wait和notify，也是基于这个ObjectMonitor来实现的，所以如果调用了wait/notify方法，就直接膨胀成重量级锁。这是JVM的设计决定的。
参考资料：
https://zhuanlan.zhihu.com/p/54638640
https://blog.51cto.com/14440216/2427707
https://juejin.im/post/6844904136069087239
