### ISSUE TITLE
第一篇第二节中的Callable、Future与FutureTask

### ISSUE THREAD

**Issue by rendeyuwei** [RedSpider1/concurrent#68]
> JDK提供了Callable接口与Future类为我们解决这个问题，这也是所谓的“异步”模型。

此处笔误，应该是Future接口吧

**Comment by initial-y** [comment]
> > JDK提供了Callable接口与Future类为我们解决这个问题，这也是所谓的“异步”模型。
> 
> 此处笔误，应该是Future接口吧

感谢指出，已修改。
