### ISSUE TITLE
12.2.3章节关于ThreadPoolExecutor处理线程过程的示意图有疑问

### ISSUE THREAD

**Issue by ambition0802** [RedSpider1/concurrent#69]
下图红框中的描述是否不严谨，非核心的线程也能消费缓冲队列中的任务吧？
看ThreadPollExecutor的源码，核心线程和所谓的非核心线程都是放在同一个HashSet中
` private final HashSet<Worker> workers = new HashSet<Worker>();`
![image](https://user-images.githubusercontent.com/30753647/83032859-f1ae5b00-a068-11ea-8683-6f775a945b87.png)

**Comment by yasinshaw** [comment]
感谢反馈。
非核心线程也能消费，但是这里指出是“核心线程”，因为这个时候非核心线程还没有创建，强调了后面一步的非核心线程的创建条件。
这里其实是符合逻辑的，如果任务队列没满，这个时候是不会创建非核心线程的。
当然了，也有这种情况：可能之前队列满了，创建了非核心线程，后面队列没满，这个时候非核心线程当然也可以去消费。
但这个图是为了描述整个线程池的运作过程，包括核心线程和非核心线程的创建条件，所以这里还是放“核心线程”好一点哈。
