### ISSUE TITLE
17.1.2 Semaphore.release()是否应该在finally中被调用

### ISSUE THREAD

**Issue by ambition0802** [RedSpider1/concurrent#70]
17.1.2中Semaphore的示例代码中，Semaphore释放资源自用的release方法是不是放在finally中调用更好？实例中的代码，万一抛出异常的话，Semaphore的资源就一直释放不了了，有内存泄露的风险？
`public class SemaphoreDemo {
    static class MyThread implements Runnable {

        private int value;
        private Semaphore semaphore;

        public MyThread(int value, Semaphore semaphore) {
            this.value = value;
            this.semaphore = semaphore;
        }

        @Override
        public void run() {
            try {
                semaphore.acquire(); // 获取permit
                System.out.println(String.format("当前线程是%d, 还剩%d个资源，还有%d个线程在等待",
                        value, semaphore.availablePermits(), semaphore.getQueueLength()));
                // 睡眠随机时间，打乱释放顺序
                Random random =new Random();
                Thread.sleep(random.nextInt(1000));
                semaphore.release(); // 释放permit
                System.out.println(String.format("线程%d释放了资源", value));
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    public static void main(String[] args) {
        Semaphore semaphore = new Semaphore(3);
        for (int i = 0; i < 10; i++) {
            new Thread(new MyThread(i, semaphore)).start();
        }
    }
}`

**Comment by initial-y** [comment]
> 17.1.2中Semaphore的示例代码中，Semaphore释放资源自用的release方法是不是放在finally中调用更好？实例中的代码，万一抛出异常的话，Semaphore的资源就一直释放不了了，有内存泄露的风险？
> `public class SemaphoreDemo {
> static class MyThread implements Runnable {
> 
> ```
>     private int value;
>     private Semaphore semaphore;
> 
>     public MyThread(int value, Semaphore semaphore) {
>         this.value = value;
>         this.semaphore = semaphore;
>     }
> 
>     @Override
>     public void run() {
>         try {
>             semaphore.acquire(); // 获取permit
>             System.out.println(String.format("当前线程是%d, 还剩%d个资源，还有%d个线程在等待",
>                     value, semaphore.availablePermits(), semaphore.getQueueLength()));
>             // 睡眠随机时间，打乱释放顺序
>             Random random =new Random();
>             Thread.sleep(random.nextInt(1000));
>             semaphore.release(); // 释放permit
>             System.out.println(String.format("线程%d释放了资源", value));
>         } catch (InterruptedException e) {
>             e.printStackTrace();
>         }
>     }
> }
> 
> public static void main(String[] args) {
>     Semaphore semaphore = new Semaphore(3);
>     for (int i = 0; i < 10; i++) {
>         new Thread(new MyThread(i, semaphore)).start();
>     }
> }
> ```
> 
> }`

感谢反馈，你对内存泄漏的考量是正确的。
笔者原来主要的意图是为了说明Semaphore限流的功能，没有关注到这个细节，已修改。
