### ISSUE TITLE
第二篇第八节8.2.1 禁止重排序的StoreStore屏障会强刷缓存吗？

### ISSUE THREAD

**Issue by RoxyJNg** [RedSpider1/concurrent#71]
最后一种StoreLoad屏障会强刷缓存，开销是四种屏障中最大的。但是其实Store开头的屏障不是应该都要强刷缓存么？StoreStore屏障也没说要不要强刷
![微信截图_20200529153937](https://user-images.githubusercontent.com/19678953/83234375-ba53c180-a1c2-11ea-99de-4b261f6650a8.png)

**Comment by TeeMoCode** [comment]
可以看下原文[http://gee.cs.oswego.edu/dl/jmm/cookbook.html](url)关于StoreLoad Barriers的描述
