### ISSUE TITLE
1.1进程的提出部分疑似有错别字 “操作体统”

### ISSUE THREAD

**Issue by wangzhigang1999** [RedSpider1/concurrent#72]
![image](https://user-images.githubusercontent.com/40266193/83351550-8b328100-a377-11ea-8d7e-5ae38cf456bb.png)

**Comment by wangzhigang1999** [comment]
原文如下：

  使用进程+CPU时间片轮转方式的操作系统，在宏观上看起来同一时间段执行多个任务，换句话说，进程让操作体统的并发成为了可能。虽然并发从宏观上看有多个任务在执行，但在事实上，对于单核CPU来说，任意具体时刻都只有一个任务在占用CPU资源。

**Comment by initial-y** [comment]
> 原文如下：
> 
> 使用进程+CPU时间片轮转方式的操作系统，在宏观上看起来同一时间段执行多个任务，换句话说，进程让操作体统的并发成为了可能。虽然并发从宏观上看有多个任务在执行，但在事实上，对于单核CPU来说，任意具体时刻都只有一个任务在占用CPU资源。

感谢反馈， 此处官网已修改。参考[进程与线程的基本概念](http://concurrent.redspider.group/article/01/1.html)
