### ISSUE TITLE
章节5.3中示例代码有线程安全的问题

### ISSUE THREAD

**Issue by ambition0802** [RedSpider1/concurrent#73]
章节5.3中用volatile关键字来说明信号量的实例代码有线程安全的问题：
```
public class Signal {
    private static volatile int signal = 0;

    static class ThreadA implements Runnable {
        @Override
        public void run() {
            while (signal < 5) {
                if (signal % 2 == 0) {
                    System.out.println("threadA: " + signal);
                    synchronized (this) {
                        signal++;
                    }
                }
            }
        }
    }

    static class ThreadB implements Runnable {
        @Override
        public void run() {
            while (signal < 5) {
                if (signal % 2 == 1) {
                    System.out.println("threadB: " + signal);
                    synchronized (this) {
                        signal = signal + 1;
                    }
                }
            }
        }
    }

    public static void main(String[] args) throws InterruptedException {
        new Thread(new ThreadA()).start();
        Thread.sleep(1000);
        new Thread(new ThreadB()).start();
    }
}

// 输出：
threadA: 0
threadB: 1
threadA: 2
threadB: 3
threadA: 4
```
下面这三行的代码整体需要保证原子性“ while (signal < 5)  、if (signal % 2 == 0) 、signal++;”，否则会有线程安全的问题。
假设此时signal=4，ThreadA和ThreadB都刚执行完while (signal < 5)这一行，进入while的循环体内。此时ThreadB没有分到CPU时间片，ThreadA继续执行，跑完接下来的逻辑后，signal变成了5，此时ThreadB才刚开始从“ if (signal % 2 == 1) ”这一行继续往下执行，最终signal=6
因为示例代码中，signal必须要小于5，所以运行实例代码时，难以出现线程安全的场景，但是如果将signal的范围从signal<5,改成signal < 50,运行多次实例代码，会出现下面两种运行结果：
结果1：
threadA: 0
threadB: 1
threadA: 2
threadB: 3
······
······
threadB: 47
threadA: 48
threadB: 49

结果2：
threadA: 0
threadB: 1
threadA: 2
threadB: 3
······
······
threadB: 47
threadA: 48
threadB: 49
threadA: 50

**Comment by yasinshaw** [comment]
言之有理，感谢反馈。这里主要是想表达volatile变量的可见性，所以没有考虑到其它方面，我们会在文中备注一下。
