### ISSUE TITLE
第一篇第3节:线程组和线程优先级,中如果所以不是很通顺

### ISSUE THREAD

**Issue by Gingigo** [RedSpider1/concurrent#74]
如果某线程是守护线程，那**如果所以**的非守护线程结束，这个守护线程也会自动结束

**Comment by Gingigo** [comment]
改成“如果某线程是守护线程，那如果所有的非守护线程都结束了，这个守护线程也会自动结束。”会更加合理

**Comment by initial-y** [comment]
> 改成“如果某线程是守护线程，那如果所有的非守护线程都结束了，这个守护线程也会自动结束。”会更加合理

感谢反馈， 已修改
