### ISSUE TITLE
章节"8.2.1 禁止重排序"中volatile与普通变量的重排序规则第三条疑问

### ISSUE THREAD

**Issue by TeeMoCode** [RedSpider1/concurrent#77]
原文如下:
"再介绍一下volatile与普通变量的重排序规则:

如果第一个操作是volatile读，那无论第二个操作是什么，都不能重排序；

如果第二个操作是volatile写，那无论第一个操作是什么，都不能重排序；

如果第一个操作是volatile写，第二个操作是volatile读，那不能重排序。"

原文第三条是"如果第一个操作是volatile写，第二个操作是volatile读，那不能重排序。"按照Doug Lea大师的一篇文章[《The JSR-133 Cookbook for Compiler Writers》](http://gee.cs.oswego.edu/dl/jmm/cookbook.html),如果第一个操作是volatile写，第二个操作是volatile读或者volatile写，那不能重排序。

**Comment by chenxiao19920206** [comment]
“如果第一个操作是volatile写，第二个操作是volatile写”已经包含在了第二条中。

**Comment by TeeMoCode** [comment]
> “如果第一个操作是volatile写，第二个操作是volatile写”已经包含在了第二条中。

的确是这样,已经描述过了,我之前算重复了

<table border="1" cellspacing="1" cellpadding="1">
  <tbody>
  <tr>
    <td align="center"><b>Can Reorder</b>
    </td>
    <td colspan="4" rowspan="1" align="center"><em>2nd operation</em>
    </td>
  </tr>
  <tr>
    <td><em>1st operation</em>
    </td>
    <td>Normal Load<br>Normal Store
    </td>
    <td>Volatile Load <br> MonitorEnter
    </td>
    <td>Volatile Store <br> MonitorExit
    </td>
  </tr>
  <tr>
    <td>Normal Load<br>Normal Store
    </td>
    <td><br>
    </td>
    <td><br>
    </td>
    <td>No
    </td>
  </tr>
  <tr>
    <td>Volatile Load <br> MonitorEnter
    </td>
    <td>No
    </td>
    <td>No
    </td>
    <td>No
    </td>
  </tr>
  <tr>
    <td>Volatile store <br> MonitorExit
    </td>
    <td><br>
    </td>
    <td>No
    </td>
    <td>No
    </td>
  </tr>
  
  </tbody>    
</table>
