### ISSUE TITLE
章节"11.4.1 获取资源"最后总结的流程图疑问

### ISSUE THREAD

**Issue by TeeMoCode** [RedSpider1/concurrent#78]
![image](https://user-images.githubusercontent.com/23631025/84463403-42969400-aca4-11ea-8add-800f1d62db8d.png)

原图中acquire方法调用的tryAquire()方法,如果结果为true,自己中断线程;而查看AQS源码
``` java
public final void acquire(int arg) {
	if (!tryAcquire(arg) && acquireQueued(addWaiter(Node.EXCLUSIVE), arg))
	selfInterrupt();
}
```
可以看到如果tryAcquire()结果为true,那么!tryAcquire()的结果为false,不会执行 selfInterrupt();而是执行获取到锁后的代码

**Comment by yasinshaw** [comment]
#47  已修复，直接关闭。
