### ISSUE TITLE
章节【8 volatitle】中配图丢失

### ISSUE THREAD

**Issue by Arther1228** [RedSpider1/concurrent#81]
详细：【8.2.1 内存可见性】 中的《volatile内存示意图》《内存屏障》 丢失；

**Comment by MarkHe1222** [comment]
https://redspider.gitbook.io/concurrent/di-er-pian-yuan-li-pian/8
图床丢失

**Comment by yasinshaw** [comment]
应该是路径问题，推荐看在线版本http://concurrent.redspider.group
