### ISSUE TITLE
关于重量级锁不使用自旋的前后矛盾

### ISSUE THREAD

**Issue by zhangyi0412** [RedSpider1/concurrent#82]
9.2.6表格中提到,重量级锁没有自旋.
9.2.4中提到成为继承者,也是需要自旋抢锁.
上面两点不是矛盾了么?

**Comment by initial-y** [comment]
你好 感谢反馈, 这里应该是在争夺锁的过程中, 偏向锁到轻量级锁, 轻量级锁到重量级锁的升级过程中会发生自旋.
