### ISSUE TITLE
1.1进程产生的背景错别字

### ISSUE THREAD

**Issue by xuerldx** [RedSpider1/concurrent#83]
后来有了批处理**操作体统**,把一系列需要操作的指令写下来，形成一个清单，一次性交给计算机。用户将多个需要执行的程序写在磁带上，然后交由计算机去读取并逐个执行这些程序，并将输出结果写在另一个磁带上。 --> **"操作体统"应该为"操作系统"**

总之，进程和线程的提出极大的提高了**操作提供**的性能。进程让操作系统的并发性成为了可能，而线程让进程的内部并发成为了可能。 --> **“操作提供”应该为“操作系统”**

**Comment by initial-y** [comment]
你好, 已经修复, 最新文档请关注 [多线程](http://concurrent.redspider.group/)
