### ISSUE TITLE
第一篇 第4节  4.3.1 BLOCKED与RUNNABLE状态的转换  demo 结论有误

### ISSUE THREAD

**Issue by Chensusie** [RedSpider1/concurrent#86]
blockedTest():1 测试主线程没有 sleep(1000L)  的 demo
2 测试主线程中有sleep(1000L) 的demo
打印的结果应该是有多种情况的,并不是唯一或确定的.

**Comment by initial-y** [comment]
感谢勘误, 你说的是对的, 有没有sleep并不能完全保证输出的唯一性,会尽快修复
