### ISSUE TITLE
2.2.3FutureTask类例程，没有抛出异常

### ISSUE THREAD

**Issue by mapleafly** [RedSpider1/concurrent#88]
// 自定义Callable，与上面一样
class Task implements Callable<Integer>{
    @Override
    public Integer call() throws Exception {
        // 模拟计算需要一秒
        Thread.sleep(1000);
        return 2;
    }
    public static void main(String args[]){
        // 使用
        ExecutorService executor = Executors.newCachedThreadPool();
        FutureTask<Integer> futureTask = new FutureTask<>(new Task());
        executor.submit(futureTask);
        System.out.println(futureTask.get());
    }
}

futureTask.get()需要抛出异常

**Comment by initial-y** [comment]
严谨, 感谢反馈, 已修复
