### ISSUE TITLE
#拼写错误

### ISSUE THREAD

**Issue by zgf138** [RedSpider1/concurrent#89]
https://redspider.gitbook.io/concurrent/di-yi-pian-ji-chu-pian/4#43-xian-cheng-zhuang-tai-de-zhuan-huan
4.3线程状态转换图
![image](https://user-images.githubusercontent.com/36942173/88145702-6cd95b00-cc2d-11ea-9a23-482e0fa79916.png)TERMIATED

https://redspider.gitbook.io/concurrent/di-er-pian-yuan-li-pian/10#104-yuan-zi-cao-zuo-atomicinteger-lei-yuan-ma-jian-xi
10.4根据本文第一篇参考文章（文末链接），它跟volitile有关。

**Comment by initial-y** [comment]
感谢指出, 已经修复
