### ISSUE TITLE
第一篇第四节BLOCKED与RUNNABLE状态的转换

### ISSUE THREAD

**Issue by Lemon158** [RedSpider1/concurrent#92]
不设置main的休息时间，测试之后出现的情况有两种。情况1：a：runnable，b:bolcked;情况2 a：runnable，b：runnable

**Comment by initial-y** [comment]
你好, 感谢指出, 你的说法是对的.
就算不指定main线程的sleep(), 方法 具体的调度也需要看时间片的分配.
会尽快修复
