### ISSUE TITLE
ThreadLocal类的原理啥时候写啊

### ISSUE THREAD

**Issue by lizengcai** [RedSpider1/concurrent#99]
![image](https://user-images.githubusercontent.com/21332397/96558005-95afd180-12aa-11eb-9245-974b2823245a.png)

**Comment by JedLee6** [comment]
是的，我今天也看到这个部分，于是就来到github地址来找有没有更新的内容了，结果比较可惜，作者还没更新，作者加油呀。

**Comment by yasinshaw** [comment]
补上补上，尽快补上。大家可以先看看这个：https://yasinshaw.com/articles?keyword=threadlocal
